#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running unit tests..."
npx vitest run

echo "Running integration tests..."
npm run test:integration

echo "Checking types..."
npm run typecheck

echo "Running lint..."
npm run lint
